# Generated by rust2rpm 17
%bcond_without check
%global __cargo_skip_build 0

%global crate exa

Name:           rust-%{crate}
Version:        0.10.1
Release:        1%{?dist}
Summary:        Modern replacement for ls

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/exa
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Modern replacement for ls.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%{_bindir}/exa

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Jul 12 01:16:57 PST 2021 rivenirvana <acverain@up.edu.ph> - 0.10.1-1
- Initial package
